version: "3"
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: jinnah_tech_assignment_db
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - mysqlvolume:/var/lib/mysql
    networks:
      - blog
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/blog-api
      - /tmp/blog-api/mysqld:/run/mysqld
    depends_on:
      - db
    networks:
      - blog
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - blog
volumes:
  mysqlvolume:
networks:
  blog:
